### ISSUE TITLE
Unknown tag 'leaflet_map'

### ISSUE THREAD

**Issue by jvanulde** [DavidJVitale/jekyll-leaflet#4]
Added the gem according to the instructions at: https://davidjvitale.com/tech/jekyll-leaflet/getting-started/ 

When executing `bundle exec jekyll serve --baseurl ''` I get the following error:

    Error: Liquid syntax error (line 3): Unknown tag 'leaflet_map'

**Comment by DavidJVitale** [comment]
Thanks so much @jvanulde . I deployed the new site, https://davidjvitale.com/tech/jekyll-leaflet/getting-started/ contains the new fix.
